name: pcsx2-tabetai # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Sony PlayStation 2 emulator. # 79 char long summary
description: |
 PCSX2 is a Playstation 2 'emulator'.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pcsx2-tabetai: 
    command: desktop-launch $SNAP/bin/PCSX2
    plugs: [network, network-bind, x11, opengl, home, alsa, pulseaudio, bluez, joystick, raw-usb, removable-media, wayland, unity7]
    desktop: share/applications/PCSX2.desktop


parts:
  enable-i386:
    plugin: nil
    prepare: |
      dpkg --add-architecture i386
      apt-get update
  pcsx2-tabetai:
    source: https://github.com/PCSX2/pcsx2.git
    plugin: cmake
    configflags:
          - -DCMAKE_BUILD_TYPE=Release
          - -DCMAKE_BUILD_STRIP=FALSE
          - -DXDG_STD=TRUE
          - -DDISABLE_ADVANCE_SIMD=TRUE
          - -DPACKAGE_MODE=TRUE
          - -DGSDX_LEGACY=TRUE
    build-packages:
           - libaio-dev:i386
           - libasound2-dev:i386
           - libbz2-dev:i386
           - libegl1-mesa-dev:i386
           - libgl1-mesa-dev:i386
           - libglew-dev:i386
           - libglu1-mesa-dev:i386
           - libgtk2.0-dev:i386
           - libjpeg-dev:i386
           - libsdl2-dev:i386
           - libsoundtouch-dev:i386
           - libsparsehash-dev:i386
           - libwxbase3.0-dev:i386
           - libwxgtk3.0-dev:i386
           - libx11-dev:i386
           - nvidia-cg-dev:i386
           - portaudio19-dev:i386
           - zlib1g-dev:i386
           - libpng++-dev:i386
           - libpng-dev:i386
           - liblzma-dev:i386
           - libudev-dev:i386
    stage-packages:
           - libaio1:i386
           - libasound2:i386
           - libc6:i386
           - libgcc1:i386
           - libgdk-pixbuf2.0-0:i386
           - libgl1-mesa-glx:i386
           - libglib2.0-0:i386
           - libgtk2.0-0:i386
           - liblzma5:i386
           - libpng12-0:i386
           - libportaudio2:i386
           - libsdl2-2.0-0:i386
           - libsoundtouch1:i386
           - libstdc++6:i386
           - libwxbase3.0-0v5:i386
           - libwxgtk3.0-0v5:i386
           - libx11-6:i386
           - zlib1g:i386 
    after: [desktop-gtk2]
    after: [enable-i386]
