name: pcsx2-tabetai # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Sony PlayStation 2 emulator. # 79 char long summary
description: |
  PCSX2 is a Playstation 2 'emulator', a free program that tries to replicate the      	 Playstation 2 console to enable you to play PS2 games on your PC.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  pcsx2-tabetai: 
    command: desktop-launch $SNAP/bin/PCSX2
    plugs: [network, network-bind, x11, opengl, home, alsa, pulseaudio, bluez, joystick, raw-usb, removable-media, wayland, unity7]
    desktop: usr/share/applications/PCSX2.desktop


parts:
  pcsx2-tabetai:
    plugin: cmake
    source-type: git
    source: https://github.com/PCSX2/pcsx2.git
    build-packages:
      - libaio-dev
      - libasound2-dev
      - libbz2-dev
      - libcg
      - libcggl
      - libegl1-mesa-dev
      - libgl1-mesa-dev
      - libglew-dev
      - libglu1-mesa-dev
      - libgtk2.0-dev
      - libjpeg-dev
      - libsdl1.2-dev
      - libsoundtouch-dev
      - libsparsehash-dev
      - libwxbase3.0-dev
      - libwxgtk3.0-dev
      - libx11-dev
      - nvidia-cg-dev
      - nvidia-cg-toolkit
      - portaudio19-dev
      - zlib1g-dev
    after: [desktop-gtk3]
